# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CartasGPT
email: thlira15@gmail.com
baseurl: "/CartasGPT/" 
url: "https://thiagolira.github.io/" 
github_username:  ThiagoLira

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
  - /indexes/Verde_index.md
  - /indexes/Vinci_index.md
collections:
  Verde:
    permalink: /:collection/:path.html
    index_permalink: /Verde/
    output: true
  Vinci:
    permalink: /:collection/:path.html
    index_permalink: /Vinci/
    output: true
  Itau:
    permalink: /:collection/:path.html
    index_permalink: /Itau/
    output: true
  Hashdex:
    permalink: /:collection/:path.html
    index_permalink: /Hashdex/
    output: true
  JGP:
    permalink: /:collection/:path.html
    index_permalink: /JGP/
    output: true
  Kinea:
    permalink: /:collection/:path.html
    index_permalink: /Kinea/
  Alaska_Asset:
          permalink: /:collection/:path.html
          index_permalink: /Alaska_Asset/
          output: true
  Apex_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Apex_Capital/
          output: true
  Armor_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Armor_Capital/
          output: true
  ASA_Hedge:
          permalink: /:collection/:path.html
          index_permalink: /ASA_Hedge/
          output: true
  Atmosphere_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Atmosphere_Capital/
          output: true
  AZ_Quest:
          permalink: /:collection/:path.html
          index_permalink: /AZ_Quest/
          output: true
  BNP_Asset_Management:
          permalink: /:collection/:path.html
          index_permalink: /BNP_Asset_Management/
          output: true
  Canvas_Vector:
          permalink: /:collection/:path.html
          index_permalink: /Canvas_Vector/
          output: true
  Clave_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Clave_Capital/
          output: true
  Dahlia_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Dahlia_Capital/
          output: true
  Gap_Asset:
          permalink: /:collection/:path.html
          index_permalink: /Gap_Asset/
          output: true
  Garde:
          permalink: /:collection/:path.html
          index_permalink: /Garde/
          output: true
  Genoa_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Genoa_Capital/
          output: true
  Ibiuna_Crédito:
          permalink: /:collection/:path.html
          index_permalink: /Ibiuna_Crédito/
          output: true
  Ibiuna_Hedge_STH:
          permalink: /:collection/:path.html
          index_permalink: /Ibiuna_Hedge_STH/
          output: true
  Ibiuna_Long_Short:
          permalink: /:collection/:path.html
          index_permalink: /Ibiuna_Long_Short/
          output: true
  Indie_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Indie_Capital/
          output: true
  Infinity_Asset:
          permalink: /:collection/:path.html
          index_permalink: /Infinity_Asset/
          output: true
  Itaú_BBA:
          permalink: /:collection/:path.html
          index_permalink: /Itaú_BBA/
          output: true
  JGP_Idex-CDI:
          permalink: /:collection/:path.html
          index_permalink: /JGP_Idex-CDI/
          output: true
  Kapitalo_K10:
          permalink: /:collection/:path.html
          index_permalink: /Kapitalo_K10/
          output: true
  Kapitalo_Kappa:
          permalink: /:collection/:path.html
          index_permalink: /Kapitalo_Kappa/
          output: true
  Kapitalo_Zeta:
          permalink: /:collection/:path.html
          index_permalink: /Kapitalo_Zeta/
          output: true
  Legacy_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Legacy_Capital/
          output: true
  Mar_Asset:
          permalink: /:collection/:path.html
          index_permalink: /Mar_Asset/
          output: true
  Meta_Asset_Management:
          permalink: /:collection/:path.html
          index_permalink: /Meta_Asset_Management/
          output: true
  Occam_Investimentos:
          permalink: /:collection/:path.html
          index_permalink: /Occam_Investimentos/
          output: true
  parse.py:
          permalink: /:collection/:path.html
          index_permalink: /parse.py/
          output: true
  RPS_Capital:
          permalink: /:collection/:path.html
          index_permalink: /RPS_Capital/
          output: true
  Somma_Investimentos:
          permalink: /:collection/:path.html
          index_permalink: /Somma_Investimentos/
          output: true
  Sparta:
          permalink: /:collection/:path.html
          index_permalink: /Sparta/
          output: true
  SPX:
          permalink: /:collection/:path.html
          index_permalink: /SPX/
          output: true
  Tenax_Capital:
          permalink: /:collection/:path.html
          index_permalink: /Tenax_Capital/
          output: true
  Titanium_Asset:
          permalink: /:collection/:path.html
          index_permalink: /Titanium_Asset/
          output: true
  Trafalgar_Investimentos:
          permalink: /:collection/:path.html
          index_permalink: /Trafalgar_Investimentos/
          output: true
  Verde_Asset_Management:
          permalink: /:collection/:path.html
          index_permalink: /Verde_Asset_Management/
          output: true
  XP_Asset:
          permalink: /:collection/:path.html
          index_permalink: /XP_Asset/
          output: true   
