# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CartasGPT - BETA
email: thlira15@gmail.com
baseurl: "" 
url: "https://www.cartasgpt.com.br" 
github_username:  ThiagoLira

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
  - metodologia.md
collections:
  Transcricoes:
    permalink: /:collection/:path.html
    index_permalink: /Transcricoes/
    output: true
  Alaska_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Alaska_Asset_Management/
    output: true
  Apex_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Apex_Capital/
    output: true
  Armor_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Armor_Capital/
    output: true
  ASA_Investments:
    permalink: /:collection/:path.html
    index_permalink: /ASA_Investments/
    output: true
  Atmosphere_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Atmosphere_Capital/
    output: true
  AZ_Quest_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /AZ_Quest_Investimentos/
    output: true
  BB_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /BB_Asset_Management/
    output: true
  Bradesco_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Bradesco_Asset_Management/
    output: true
  BV_Asset:
    permalink: /:collection/:path.html
    index_permalink: /BV_Asset/
    output: true
  Caixa_Asset:
    permalink: /:collection/:path.html
    index_permalink: /Caixa_Asset/
    output: true
  Canvas_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Canvas_Capital/
    output: true
  Dahlia_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Dahlia_Capital/
    output: true
  Garde_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Garde_Asset_Management/
    output: true
  Genoa_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Genoa_Capital/
    output: true
  Ibiuna_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /Ibiuna_Investimentos/
    output: true
  Indie_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Indie_Capital/
    output: true
  Infinity_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Infinity_Asset_Management/
    output: true
  Itau_BBA:
    permalink: /:collection/:path.html
    index_permalink: /Itau_BBA/
    output: true
  Kapitalo:
    permalink: /:collection/:path.html
    index_permalink: /Kapitalo/
    output: true
  Legacy_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Legacy_Capital/
    output: true
  Mar_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Mar_Asset_Management/
    output: true
  Meta_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Meta_Asset_Management/
    output: true
  Occam_Brasil:
    permalink: /:collection/:path.html
    index_permalink: /Occam_Brasil/
    output: true
  Opportunity:
    permalink: /:collection/:path.html
    index_permalink: /Opportunity/
    output: true
  Porto_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Porto_Asset_Management/
    output: true
  Rio_Bravo:
    permalink: /:collection/:path.html
    index_permalink: /Rio_Bravo/
    output: true
  RPS_Capital_Investment_Management:
    permalink: /:collection/:path.html
    index_permalink: /RPS_Capital_Investment_Management/
    output: true
  Santander_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Santander_Asset_Management/
    output: true
  Sicredi_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Sicredi_Asset_Management/
    output: true
  Somma_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /Somma_Investimentos/
    output: true
  Sparta_Fundos_de_Investimento:
    permalink: /:collection/:path.html
    index_permalink: /Sparta_Fundos_de_Investimento/
    output: true
  SPX_Capital:
    permalink: /:collection/:path.html
    index_permalink: /SPX_Capital/
    output: true
  Tenax_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Tenax_Capital/
    output: true
  Titanium_Asset:
    permalink: /:collection/:path.html
    index_permalink: /Titanium_Asset/
    output: true
  Trafalgar_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /Trafalgar_Investimentos/
    output: true
  Verde_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Verde_Asset_Management/
    output: true
  Western_Asset:
    permalink: /:collection/:path.html
    index_permalink: /Western_Asset/
    output: true
  XP_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /XP_Asset_Management/
    output: true
