# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CartasGPT - BETA
email: thlira15@gmail.com
baseurl: ""
url: "https://www.cartasgpt.com.br"
github_username:  ThiagoLira

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll@5.0.0

# Google Tag
gtag: "G-5FRQRL198F"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

navbar-links:
  Gestoras: "/gestoras"
  Feed: "/feed"
  Metodologia: "/metodologia"
  About: "/about"

collections:
  Ace_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Ace_Capital/
    output: true
  Atmos_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Atmos_Capital/
    output: true
  AZ_Quest_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /AZ_Quest_Investimentos/
    output: true
  Bradesco_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Bradesco_Asset_Management/
    output: true
  BV_Asset:
    permalink: /:collection/:path.html
    index_permalink: /BV_Asset/
    output: true
  BTG_Pactual_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /BTG_Pactual_Asset_Management/
    output: true
  Capitania_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /Capitania_Investimentos/
    output: true
  Dahlia_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Dahlia_Capital/
    output: true
  Daycoval_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Daycoval_Asset_Management/
    output: true
  Dynamo:
    permalink: /:collection/:path.html
    index_permalink: /Dynamo/
    output: true
  Gap Asset:
    permalink: /:collection/:path.html
    index_permalink: /Gap_Asset/
    output: true
  Genoa_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Genoa_Capital/
    output: true
  Icatu_Vanguarda:
    permalink: /:collection/:path.html
    index_permalink: /Icatu_Vanguarda/
    output: true
  JGP_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /JGP_Asset_Management/
    output: true
  Legacy_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Legacy_Capital/
    output: true
  MAG_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /MAG_Investimentos/
    output: true
  O3_Capital:
    permalink: /:collection/:path.html
    index_permalink: /O3_Capital/
    output: true
  Occam_Brasil:
    permalink: /:collection/:path.html
    index_permalink: /Occam_Brasil/
    output: true
  Opportunity:
    permalink: /:collection/:path.html
    index_permalink: /Opportunity/
    output: true
  Porto_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Porto_Asset_Management/
    output: true
  Rio_Bravo:
    permalink: /:collection/:path.html
    index_permalink: /Rio_Bravo/
    output: true
  Santander_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Santander_Asset_Management/
    output: true
  Sicredi_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Sicredi_Asset_Management/
    output: true
  SPX_Capital:
    permalink: /:collection/:path.html
    index_permalink: /SPX_Capital/
    output: true
  Sueste_Capital:
    permalink: /:collection/:path.html
    index_permalink: /Sueste_Capital/
    output: true
  SulAmerica_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /SulAmerica_Investimentos/
    output: true
  V8_Capital:
    permalink: /:collection/:path.html
    index_permalink: /V8_Capital/
    output: true
  Valora_Investimentos:
    permalink: /:collection/:path.html
    index_permalink: /Valora_Investimentos/
    output: true
  Verde_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /Verde_Asset_Management/
    output: true
  Western_Asset:
    permalink: /:collection/:path.html
    index_permalink: /Western_Asset/
    output: true
  WHG:
    permalink: /:collection/:path.html
    index_permalink: /WHG/
    output: true
  XP_Asset_Management:
    permalink: /:collection/:path.html
    index_permalink: /XP_Asset_Management/
    output: true
