# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CartasGPT
email: thlira15@gmail.com
baseurl: "/CartasGPT/" 
url: "https://thiagolira.github.io/" 
github_username:  ThiagoLira

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
  - /indexes/Verde_index.md
  - /indexes/Vinci_index.md
collections:
  Verde:
    permalink: /:collection/:path.html
    index_permalink: /Verde/
    output: true
  Vinci:
    permalink: /:collection/:path.html
    index_permalink: /Vinci/
    output: true
  Itau:
    permalink: /:collection/:path.html
    index_permalink: /Itau/
    output: true
  Hashdex:
    permalink: /:collection/:path.html
    index_permalink: /Hashdex/
    output: true
  JGP:
    permalink: /:collection/:path.html
    index_permalink: /JGP/
    output: true
  Kinea:
    permalink: /:collection/:path.html
    index_permalink: /Kinea/
    output: true
